# Generated by Django 5.2.5 on 2025-09-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='專案名稱')),
                ('llm_model', models.CharField(choices=[('gpt-5', 'GPT‑5'), ('gpt-4o', 'GPT‑4o'), ('local', '本地模型（Llama 等）')], max_length=50, verbose_name='LLM 模型')),
                ('embedding_engine', models.CharField(choices=[('text-embedding-3-large', 'OpenAI text-embedding-3-large'), ('bge-large', 'BGE Large'), ('cohere-v3', 'Cohere embed-english-v3')], max_length=50, verbose_name='向量化引擎')),
                ('role_prompt', models.TextField(blank=True, verbose_name='角色指令定義')),
                ('response_template', models.TextField(blank=True, verbose_name='回應模板配置')),
                ('example_prompts', models.TextField(blank=True, verbose_name='範例提示詞（每行一個）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
