# Generated by Django 5.2.5 on 2025-09-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='說明'),
        ),
        migrations.AddField(
            model_name='llmproject',
            name='project_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='專案代碼'),
        ),
        migrations.AlterField(
            model_name='llmproject',
            name='llm_model',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('gpt-5', 'GPT‑5'), ('gpt-4o', 'GPT‑4o'), ('local', 'Llama')], max_length=50, verbose_name='LLM 模型'),
        ),
    ]
