# Generated by Django 5.2.5 on 2025-09-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_llmproject_description_llmproject_project_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmproject',
            name='embedding_engine',
            field=models.CharField(blank=True, choices=[('text-embedding-3-large', 'OpenAI text-embedding-3-large'), ('bge-large', 'BGE Large'), ('cohere-v3', 'Cohere embed-english-v3')], max_length=50, null=True, verbose_name='向量化引擎'),
        ),
    ]
