# Generated by Django 5.2.5 on 2025-08-28 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='選單名稱')),
                ('url', models.CharField(max_length=200, verbose_name='連結（/path 或完整網址）')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序（小到大）')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menu', verbose_name='父選單')),
            ],
            options={
                'verbose_name': '選單',
                'verbose_name_plural': '選單',
                'ordering': ['order', 'id'],
            },
        ),
    ]
